# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171107_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
